# Dependencies
markdown:         kramdown
highlighter:      true
highlighting:     pygments

gems:
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            "psgs' Thoughts"
tagline:          "A fun 'lil blog, sharing my thoughts, interests and experiences."
description:      "A fun 'lil open-source blog, sharing my thoughts, interests and experiences."
url:              https://psgs.github.io/blog

author:
  name:           'psgs'
  url:            https://psgs.tk

paginate:         5

# Custom variables
version:          1.1.0

github:
  repo:           https://github.com/psgs/blog

# Files to exclude, as an array
exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile

#prose config, see http://prose.io/help/handbook.html
prose:
  siteurl: "https://psgs.github.io/blog"
  media: assets/img
  relativeLinks: https://psgs.github.io/blog/links.jsonp
  metadata:
    _posts:
      - name: categories
        field:
          label: Categories
          element: select
          placeholder: Select a category
          options:
            - name: Development
              value: development
            - name: Networking
              value: networking
            - name: Gaming
              value: gaming
            - name: Thoughts
              value: thoughts
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          label: Excerpt
          value: ""
      - name: author
        field:
          element: text
          label: Author
          value: psgs
      - name: comments
        field:
          element: checkbox
          label: Comments Enabled
          value: true
      - name: tags
        field:
          element: text
          label: Tags
          value: ""
    "/":
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          value: ""
      - name: id
        field:
          element: text
          value: ""
      - name: layout
        field:
          element: select
          placeholder: Select a layout
          options:
            - name: Page
              value: page
            - name: Post
              value: post
            - name: Default
              value: default
